---

- name: Install packages
  npm:
    name: pm2
    global: yes
    version: "{{ pm2_version | default(omit) }}"
  notify: update pm2

- name: Installing startup script
  become_user: "{{ pm2_user }}"
  become: yes
  command: "pm2 startup -u {{ pm2_user }}"
